# Generated by Django 4.1.6 on 2023-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_qordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qordata',
            name='x_axis',
            field=models.DateField(),
        ),
    ]
