# Generated by Django 4.1.6 on 2023-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_qordata_x_axis'),
    ]

    operations = [
        migrations.CreateModel(
            name='qordata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DateField()),
                ('y_axis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='qordata3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DateField()),
                ('y_axis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='qordata4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suites', models.CharField(max_length=122)),
            ],
        ),
    ]
